name: Linux Tests

on:
  push:
    branches:
      - meson
  pull_request:
    branches:
      - meson

jobs:
  test_meson:
    name: Meson build
    # If using act to run CI locally the github object does not exist and the usual skipping should not be enforced
    if: "github.repository != '' || github.repository == 'rgommers/scipy' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip github]') && !contains(github.ref, 'maintenance/') && !contains(github.base_ref, 'maintenance/')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Ubuntu dependencies
      run: |
        # NOTE: not the same OpenBLAS version as in upstream CI (I'm being lazy here)
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev libatlas-base-dev liblapack-dev gfortran libgmp-dev libmpfr-dev libsuitesparse-dev ccache libmpc-dev

    - name: Install Python packages
      run: |
        python -m pip install numpy setuptools wheel cython pytest pytest-xdist pybind11 pytest-xdist mpmath gmpy2 pythran ninja
        python -m pip install git+https://github.com/rgommers/meson.git@fix-cython-mixed-sources

    - name: Build SciPy
      run: |
        meson setup build --prefix=$PWD/installdir --werror
        ninja -C build -j 2

    - name: Install SciPy
      run: |
        meson install -C build

    - name: Test SciPy
      run: |
        export PYTHONPATH="$PWD/installdir/lib/python3.9/site-packages/"
        pushd installdir
        python -c "import scipy; import sys; sys.exit(int(not scipy.test(parallel=2)))"
        popd
