name: Linux Tests

on:
  push:
    branches:
      - meson
  pull_request:
    branches:
      - meson

jobs:
  test_meson:
    name: Meson build
    if: "github.repository == 'rgommers/scipy' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip github]') && !contains(github.ref, 'maintenance/') && !contains(github.base_ref, 'maintenance/')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Ubuntu dependencies
      run: |
        # NOTE: not the same OpenBLAS version as in upstream CI (I'm being lazy here)
        sudo apt-get install libopenblas-dev libatlas-base-dev liblapack-dev gfortran libgmp-dev libmpfr-dev libsuitesparse-dev ccache libmpc-dev

    - name: Install Python packages
      run: |
        python -m pip install numpy setuptools wheel cython pytest pytest-xdist pybind11 pytest-xdist mpmath gmpy2 pythran ninja
        python -m pip install --user git+https://github.com/mesonbuild/meson.git

    - name: Build SciPy
      run: |
        meson setup build --prefix=$PWD/installdir
        ninja -C build

    - name: Install SciPy
      run: |
        meson install -C build

    - name: Test SciPy
      run: |
        export PYTHONPATH=$PWD/installdir/lib/python3.9/site-packages/
        # FIXME: run all tests, not just one simple module - create a dev.py
        #        interface. Also ensure that fails CI if tests fail (see runtests.py)
        python -c "from scipy import constants as s; s.test()"
